parameters:

        database.dsn: 'mysql:host=35.238.51.199;dbname=g6'

        config:
            mobile_url: '35.232.48.192'
            tags_url: '104.155.149.209'
            supplements_url: '35.188.102.221'
            products_url: '35.226.171.250'
            system_url: 'api.system.g6nutrition.com'